#!/bin/bash
~/.cabal/bin/pandoc -N --template=template.tex --variable mainfont=Georgia --variable sansfont=Arial --variable monofont="DejaVu Sans Mono" --variable fontsize=12pt --variable lang=slovak "Budúcnosť HTML.md" --latex-engine=xelatex --toc -o "Budúcnosť HTML.pdf"
